# Generated by Django 4.1.5 on 2023-01-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handle_cnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operations', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.TextField(max_length=12)),
                ('hora', models.TimeField()),
                ('dono_da_loja', models.CharField(max_length=14)),
                ('nome_da_loja', models.CharField(max_length=19)),
            ],
        ),
    ]
